language: node_js
node_js:
- "0.8"
- "0.10"
- "0.11"
- "0.12"
- "1.0"
- "1.5"
sudo: false
script: "npm run-script test-ci"
after_script: "npm install coveralls && cat ./coverage/lcov.info | coveralls"
